### ISSUE TITLE
Improve the Add Todo and Total Expenses form

### ISSUE THREAD

**Issue by RchtDshr** [divyansh-2005/my-calendar-app#13]
The input fields on the website are spread across the full screen width, even when zooming in or out. This makes it difficult for users to interact with the form and ruins the UI. Additionally, there is no placeholder text in the input fields, and the title for which date todo is being added is not highlighted or clearly visible.

1. Go to the webpage, click on a specific date for which todo is to be added and click on Total To-Do.
2. Observe that the input fields cover the full width of the screen, regardless of zoom level.  
3. Zoom in or zoom out on the page.  
4. Notice the absence of placeholder text in the input fields and the lack of emphasis on the title.  

Expected behavior
The input fields should have a max width to prevent them from stretching across the entire screen width. There should also be placeholder text in the input fields for clarity. The title of the todo being added should be of larger font size and bold. Please assign me this issue to get the expected behavior.

Screenshots
![Screenshot 2024-10-02 205355](https://github.com/user-attachments/assets/4928539e-0b9d-4446-a804-af24dcc17934)
![Screenshot 2024-10-02 205427](https://github.com/user-attachments/assets/988bc9db-c131-4678-b9ec-7bc19c2790fc)

**Checklist**  
- [x] I am contributing under GSSoC-ext  
- [x] I am contributing under hacktoberfest  
- [x] I follow contribution guidelines
