### ISSUE TITLE
[BUG] Add an option for Add Expense and Add Todo for better UX.

### ISSUE THREAD

**Issue by RchtDshr** [divyansh-2005/my-calendar-app#14]
**Describe the bug**
There is no clear option to add expenses or todos for the selected date. The interface only displays the total expense and total todo without indicating where users can add new entries. This creates confusion for users who are unsure how to input new expenses or todos for a specific date.

**To Reproduce**  
1. Look for an option to add new expenses or todos.  
2. Notice that there is no visible or clear option to add expenses or todo.

**Expected behavior**  
In addition to showing the total expense and total todo, there should be specific options like "Add Expense" or "Add Todo" for the selected date. These options should redirect the user to the respective form where they can input their new expenses or todos. This would improve the user experience by clearly specifying the actions available for each date, thus, reducing confusion about how to add new entries.

**Screenshots**  
![image](https://github.com/user-attachments/assets/7568c388-ca62-4721-80e4-aa18a4de1bdc)

**Checklist**  
- [x] I am contributing under GSSoC-ext  
- [x] I am contributing under hacktoberfest  
- [x] I follow contribution guidelines  

Please assign me this issue to work on

**Comment by anuza08** [comment]
@RchtDshr  I can solve this issue , please assign this issue to me.

**Comment by RchtDshr** [comment]
@divyansh-2005 hey, can I work on this?

**Comment by divyansh-2005** [comment]
issue is good
we can add a sidebar to have button for Add expense and Add todo

**Comment by RchtDshr** [comment]
sure, I'll design a sidebar then. the sidebar would have option to add expense and add todo for the specific date selected (redirect to the add page). Will that work?

**Comment by anuza08** [comment]
> sure, I'll design a sidebar then. the sidebar would have option to add expense and add todo for the specific date selected (redirect to the add page). Will that work?

OK!
