### ISSUE TITLE
Irresponsive footer on expense and To-do Page

### ISSUE THREAD

**Issue by kottarivaibhav** [divyansh-2005/my-calendar-app#35]
**Describe the bug**
I have found that the footer on expense and to-do page are irresponsive . The idea I would like to implement is fix it to the bottom .

**To Reproduce**
1. Go to Home Page
2. Click on Expense/Todo to move to the respective route page
3. You will find the problem 

**Expected behavior**
To Fix the footer at the bottom .

**check list**
- [ ] I am contributing under GSSoC-ext
- [ ] I am contributing under hacktoberfest
- [ ] I follow contribution guidlines

**Additional context**
This will help in better UI/UX

**Comment by Hrishikesh-Dalal** [comment]
I would like to contribute and fix this issue

**Comment by divyansh-2005** [comment]
there no such bug, try new issues
